# Generated by Django 4.2 on 2023-05-12 12:19

import django.db.models.deletion
from django.db import migrations, models

import geoluminate.contrib.controlled_vocabulary.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geoluminate", "0002_initial"),
        ("controlled_vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestData",
            fields=[
                (
                    "geoluminate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="geoluminate.geoluminate",
                    ),
                ),
                (
                    "some_field",
                    models.CharField(
                        blank=True, help_text="Some Field", max_length=255, null=True, verbose_name="Some Field"
                    ),
                ),
                (
                    "vocab_multi",
                    geoluminate.contrib.controlled_vocabulary.fields.ControlledVocabMulti(
                        blank=True,
                        related_name="+",
                        to="controlled_vocabulary.controlledvocabulary",
                        vocab_label="test_vocab_multi",
                    ),
                ),
                (
                    "vocab_single",
                    geoluminate.contrib.controlled_vocabulary.fields.ControlledVocab(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="controlled_vocabulary.controlledvocabulary",
                        vocab_label="test_vocab_single",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Data",
                "verbose_name_plural": "Test Data",
                "permissions": [("geoluminate_database_admin", "Can access the geoluminate database admin")],
            },
            bases=("geoluminate.geoluminate",),
        ),
    ]
