# Generated by Django 4.2.10 on 2024-02-12 22:09

from django.db import migrations, models
import meta.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier for this record.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created.", verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified.", verbose_name="Modified"
                    ),
                ),
                (
                    "some_field",
                    models.CharField(
                        blank=True, help_text="Some Field", max_length=255, null=True, verbose_name="Some Field"
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Data",
                "verbose_name_plural": "Test Data",
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
