# Generated by Django 5.0.7 on 2024-08-07 15:16

import django.db.models.deletion
import geoluminate.contrib.samples.choices
import research_vocabs.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomParentSample',
            fields=[
                ('basesample_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samples.basesample')),
                ('feature_type', research_vocabs.fields.ConceptField(default='site', verbose_name='feature', vocabulary=geoluminate.contrib.samples.choices.FeatureType)),
                ('medium', research_vocabs.fields.ConceptField(default='solid', verbose_name='medium', vocabulary=geoluminate.contrib.samples.choices.SamplingMedium)),
                ('specimen_type', research_vocabs.fields.ConceptField(default='theSpecimenTypeIsUnknown', verbose_name='specimen', vocabulary=geoluminate.contrib.samples.choices.SpecimenType)),
                ('char_field', models.CharField(help_text='Enter a string of up to 200 characters.', max_length=200, verbose_name='Character Field')),
                ('parent', models.ForeignKey(blank=True, help_text='The sample from which this sample was derived.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsamples', to='samples.basesample', verbose_name='parent sample')),
            ],
            options={
                'verbose_name': 'Custom Sample',
                'verbose_name_plural': 'Custom Samples',
            },
            bases=('samples.basesample',),
        ),
        migrations.AlterField(
            model_name='customsample',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The sample from which this sample was derived.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_samples', to='example.customparentsample', verbose_name='parent sample'),
        ),
    ]
