# Generated by Django 4.2.10 on 2024-02-12 23:20

from django.db import migrations, models
import django_bleach.models
import meta.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier for this record.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created.", verbose_name="Created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified.", verbose_name="Modified"
                    ),
                ),
                (
                    "char_field",
                    models.CharField(
                        help_text="Enter a string of up to 200 characters.",
                        max_length=200,
                        verbose_name="Character Field",
                    ),
                ),
                ("text_field", django_bleach.models.BleachField(help_text="Enter a large amount of text.")),
                ("integer_field", models.IntegerField(help_text="Enter an integer.", verbose_name="Integer Field")),
                (
                    "big_integer_field",
                    models.BigIntegerField(help_text="Enter a large integer.", verbose_name="Big Integer Field"),
                ),
                (
                    "positive_integer_field",
                    models.PositiveIntegerField(
                        help_text="Enter a positive integer.", verbose_name="Positive Integer Field"
                    ),
                ),
                (
                    "positive_small_integer_field",
                    models.PositiveSmallIntegerField(
                        help_text="Enter a small positive integer.", verbose_name="Positive Small Integer Field"
                    ),
                ),
                (
                    "small_integer_field",
                    models.SmallIntegerField(help_text="Enter a small integer.", verbose_name="Small Integer Field"),
                ),
                (
                    "boolean_field",
                    models.BooleanField(default=False, help_text="Select True or False.", verbose_name="Boolean Field"),
                ),
                ("date_field", models.DateField(help_text="Select a date.", verbose_name="Date Field")),
                (
                    "date_time_field",
                    models.DateTimeField(help_text="Select a date and time.", verbose_name="Date Time Field"),
                ),
                ("time_field", models.TimeField(help_text="Select a time.", verbose_name="Time Field")),
                (
                    "decimal_field",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter a decimal number.",
                        max_digits=5,
                        verbose_name="Decimal Field",
                    ),
                ),
                (
                    "float_field",
                    models.FloatField(help_text="Enter a floating point number.", verbose_name="Float Field"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.DeleteModel(
            name="TestData",
        ),
    ]
