# Generated by Django 4.2 on 2023-05-12 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testdata",
            options={"verbose_name": "Test Data", "verbose_name_plural": "Test Data"},
        ),
    ]
