# Generated by Django 5.0.7 on 2024-08-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_customparentsample_alter_customsample_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customparentsample',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='customsample',
            name='parent',
        ),
    ]
