# Generated by Django 4.2.11 on 2024-03-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0003_alter_examplemodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examplemodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
