version: '3'
     
services:
  app: &app
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - ../:/external_apps
      - ./:/app:z
    ports:
      - "8000:8000"
    command: ./docker/django

  docs:
    <<: *app
    working_dir: /app/docs
    ports:
      - "9001:9000"
    command: ../docker/docs
