version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ghfdb
  # nginx:
  #   image: nginx:alpine
  # redis:
  #   image: redis:alpine
  web:
    container_name: Geoluminate
    build: .
    command: python geoluminate/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      # - redis
