# Generated by Django 3.2.12 on 2022-03-17 05:55

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerField(blank=True, null=True, upload_to='logos'),
        ),
    ]
