# Generated by Django 3.2.14 on 2022-07-18 10:05

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_siteconfiguration_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='icon',
            field=easy_thumbnails.fields.ThumbnailerField(blank=True, null=True, upload_to='logos'),
        ),
    ]
