# Generated by Django 3.2.15 on 2022-10-11 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crossref', '0008_auto_20221011_2213'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('work_ptr',
                 models.OneToOneField(auto_created=True,
                                      on_delete=django.db.models.deletion.CASCADE,
                                      parent_link=True,
                                      primary_key=True,
                                      serialize=False,
                                      to='crossref.work')),
                ('owner',
                 models.ForeignKey(blank=True,
                                   null=True,
                                   on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='publications',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='owner')),
            ],
            bases=('crossref.work',),
            options={
                'db_table': 'publications_publication',
            },
        ),
    ]
