# Generated by Django 3.2.16 on 2022-11-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.IntegerField(choices=[(0, 'awaiting review'), (1, 'in progress'), (2, 'verified')], default=0),
            preserve_default=False,
        ),
    ]
