# Generated by Django 3.2.15 on 2022-09-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_organizationinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationIP',
            fields=[
                ('address', models.GenericIPAddressField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('type', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchOrganization',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organization')),
                ('ROR', models.URLField(verbose_name='ROR ID')),
                ('acronyms', models.JSONField(blank=True, null=True)),
                ('addresses', models.JSONField(blank=True, null=True)),
                ('aliases', models.JSONField(blank=True, null=True)),
                ('country', models.JSONField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('established', models.IntegerField(blank=True, null=True)),
                ('external_ids', models.JSONField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_addresses', models.ManyToManyField(blank=True, null=True, to='research_organizations.OrganizationIP')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_organizations', to='research_organizations.researchorganization')),
                ('types', models.ManyToManyField(blank=True, null=True, to='research_organizations.OrganizationType')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('organizations.organization',),
        ),
    ]
