# Generated by Django 3.2.15 on 2022-09-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchorganization',
            name='types',
            field=models.ManyToManyField(blank=True, to='research_organizations.OrganizationType'),
        ),
    ]
