# Generated by Django 3.2.15 on 2022-09-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_organizations', '0002_alter_researchorganization_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchorganization',
            name='ip_addresses',
            field=models.ManyToManyField(blank=True, to='research_organizations.OrganizationIP'),
        ),
    ]
