# Generated by Django 3.2.15 on 2022-09-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_organizations', '0003_alter_researchorganization_ip_addresses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchorganization',
            options={'verbose_name': 'Research Organization', 'verbose_name_plural': 'Research Organizations'},
        ),
    ]
