# Generated by Django 4.2.11 on 2024-03-27 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geoluminate", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={
                "ordering": ["created"],
                "verbose_name": "Sample",
                "verbose_name_plural": "Samples",
            },
        ),
    ]
