# Generated by Django 4.2.1 on 2023-05-10 16:44

import literature.fields
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("literature", "0001_initial"),
        ("geoluminate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="geoluminate",
            name="literature",
            field=literature.fields.LiteratureM2M(
                blank=True,
                help_text="Associated literature.",
                to="literature.literature",
                verbose_name="literature",
            ),
        ),
        migrations.CreateModel(
            name="GeoluminateSite",
            fields=[],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("geoluminate.geoluminate",),
        ),
    ]
