# Generated by Django 3.2.17 on 2023-02-11 12:13

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geoluminate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalconfiguration',
            options={'verbose_name': 'Configuration'},
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='disable_api',
            field=models.BooleanField(default=False, help_text='Prevents access to the database API.', verbose_name='Disable API'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='disable_site',
            field=models.BooleanField(default=False, verbose_name='Disable API'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='lockdown_enabled',
            field=models.BooleanField(default=False, help_text='Locks down the entire application so that only administrators can log in.', verbose_name='lock down site'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='remote_addr_exceptions',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.GenericIPAddressField(), default=list, help_text='A list of remote IP adresses that are permitted to access the application when lockdown is enabled.', size=None, verbose_name='Remote address exceptions'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='trusted_proxies',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.GenericIPAddressField(), default=list, help_text='A list of trusted proxies.', size=None, verbose_name='Trusted proxies'),
        ),
    ]
