# Generated by Django 4.2 on 2023-05-04 15:03

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import geoluminate.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("geoluminate", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geoluminate",
            options={
                "permissions": [
                    (
                        "geoluminate_database_admin",
                        "Can create, view, update or delete any model associated with the research database",
                    )
                ],
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
            },
        ),
        migrations.AddField(
            model_name="geoluminate",
            name="IGSN",
            field=models.IntegerField(
                blank=True,
                help_text="An International Generic Sample Number for the site.",
                null=True,
                verbose_name="IGSN",
            ),
        ),
        migrations.AddField(
            model_name="geoluminate",
            name="elevation",
            field=geoluminate.db.fields.RangeField(
                blank=True,
                help_text="elevation with reference to mean sea level (m)",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(9000),
                    django.core.validators.MinValueValidator(-12000),
                ],
                verbose_name="elevation (m)",
            ),
        ),
        migrations.AddField(
            model_name="geoluminate",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="geoluminate",
            name="name",
            field=models.CharField(
                help_text="Specified site name for the related database entry",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
    ]
