# Generated by Django 4.2 on 2023-05-04 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geoluminate", "0002_alter_geoluminate_options_geoluminate_igsn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoluminateSite",
            fields=[],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("geoluminate.geoluminate",),
        ),
        migrations.AlterModelOptions(
            name="geoluminate",
            options={
                "permissions": [
                    (
                        "geoluminate_database_admin",
                        "Can create, view, update or delete any model associated with the research database",
                    )
                ],
                "verbose_name": "Geoluminate",
                "verbose_name_plural": "Geoluminate",
            },
        ),
    ]
