# Generated by Django 4.2.11 on 2024-03-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geoluminate", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "database_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="database name"
                    ),
                ),
                (
                    "database_short_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="database short name"
                    ),
                ),
                ("authority", models.JSONField(default=dict, verbose_name="authority")),
                ("theme", models.JSONField(default=dict, verbose_name="theme")),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
