# Generated by Django 3.2.17 on 2023-02-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoluminate', '0003_auto_20230211_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfiguration',
            name='enable_api',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=True, help_text='Enable or disable access to the database API.', verbose_name='Status'),
        ),
    ]
