# Generated by Django 4.2 on 2023-05-04 17:15

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("geoluminate", "0003_geoluminatesite_alter_geoluminate_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelDescriptions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("description", djangocms_text_ckeditor.fields.HTMLField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name": "Model Description",
                "verbose_name_plural": "Model Descriptions",
            },
        ),
    ]
