# Generated by Django 4.2 on 2023-05-04 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geoluminate", "0004_modeldescriptions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modeldescriptions",
            name="object_id",
        ),
    ]
