# Generated by Django 4.2.11 on 2024-03-26 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geoluminate", "0004_delete_siteconfiguration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={
                "ordering": ["created"],
                "verbose_name": "Heat Flow",
                "verbose_name_plural": "Heat Flow",
            },
        ),
    ]
