# Generated by Django 3.2.17 on 2023-02-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoluminate', '0004_alter_globalconfiguration_enable_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfiguration',
            name='lockdown_enabled',
            field=models.BooleanField(choices=[(True, 'Admin only'), (False, 'Public')], default=False, help_text='Locks down the entire application so that only administrators can log in.', verbose_name='Access rights'),
        ),
    ]
