# Generated by Django 4.2 on 2023-05-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("geoluminate", "0005_remove_modeldescriptions_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modeldescriptions",
            name="content_type",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
        ),
    ]
