# Generated by Django 3.2.18 on 2023-03-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoluminate', '0005_alter_globalconfiguration_lockdown_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoluminate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='globalconfiguration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
