# Generated by Django 4.1.5 on 2023-03-03 17:31

from django.db import migrations, models
import django.db.models.deletion
import literature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('literature', '0002_alter_literature_authors'),
        ('geoluminate', '0006_auto_20230301_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoluminate',
            name='literature',
            field=literature.fields.LiteratureM2M(blank=True, help_text='Associated literature.', to='literature.literature', verbose_name='literature'),
        ),
        migrations.AlterField(
            model_name='geoluminate',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
