# Generated by Django 5.0.7 on 2024-08-13 13:34

import django.core.validators
import meta.models
import quantityfield.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the location.",
                        max_length=255,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="The x-coordinate of the location.",
                        max_digits=9,
                        null=True,
                        verbose_name="x",
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="The y-coordinate of the location.",
                        max_digits=9,
                        null=True,
                        verbose_name="y",
                    ),
                ),
                (
                    "elevation",
                    quantityfield.fields.QuantityField(
                        base_units="m",
                        blank=True,
                        help_text="Elevation with reference to mean sea level",
                        null=True,
                        unit_choices=["m", "ft"],
                        validators=[
                            django.core.validators.MaxValueValidator(9000),
                            django.core.validators.MinValueValidator(-12000),
                        ],
                        verbose_name="elevation",
                    ),
                ),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
