# Generated by Django 5.0.7 on 2024-08-08 12:50

import django.contrib.gis.db.backends.base.models
import django.contrib.gis.db.models.fields
import django.core.validators
import meta.models
import quantityfield.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostGISGeometryColumns',
            fields=[
                ('f_table_catalog', models.CharField(max_length=256)),
                ('f_table_schema', models.CharField(max_length=256)),
                ('f_table_name', models.CharField(max_length=256)),
                ('f_geometry_column', models.CharField(max_length=256)),
                ('coord_dimension', models.IntegerField()),
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'geometry_columns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostGISSpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(max_length=256)),
                ('auth_srid', models.IntegerField()),
                ('srtext', models.CharField(max_length=2048)),
                ('proj4text', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
            bases=(models.Model, django.contrib.gis.db.backends.base.models.SpatialRefSysMixin),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this record was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When this record was last modified.', verbose_name='Modified')),
                ('name', models.CharField(blank=True, help_text='The name of the location.', max_length=255, null=True, verbose_name='name')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('elevation', quantityfield.fields.QuantityField(base_units='m', blank=True, help_text='Elevation with reference to mean sea level', null=True, unit_choices=['m', 'ft'], validators=[django.core.validators.MaxValueValidator(9000), django.core.validators.MinValueValidator(-12000)], verbose_name='elevation')),
            ],
            options={
                'verbose_name': 'sampling location',
                'verbose_name_plural': 'sampling locations',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
