# Generated by Django 5.0.7 on 2024-08-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
    ]
