# Generated by Django 4.2 on 2023-05-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controlled_vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_af",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ar_dz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ast",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_az",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_be",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_bg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_bn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_br",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_bs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ckb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_cs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_cy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_da",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_dsb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_el",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_en_au",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_en_gb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_eo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_es_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_es_co",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_es_mx",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_es_ni",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_es_ve",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_eu",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_fa",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_fi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_fy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ga",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_gd",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_gl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_he",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_hi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_hr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_hsb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_hu",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_hy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ia",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ig",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ind",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_io",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_is",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ja",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ka",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_kab",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_kk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_km",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_kn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ko",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ky",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_lb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_lt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_lv",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_mk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ml",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_mn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_mr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_my",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_nb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ne",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_nn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_os",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_pa",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_pl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_pt_br",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ro",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_sk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_sl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_sq",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_sr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_sr_latn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_sv",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_sw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ta",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_te",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_tg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_th",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_tk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_tr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_tt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_udm",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_uk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_ur",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_vi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_zh_hans",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="description_zh_hant",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_af",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ar_dz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ast",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_az",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_be",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_bg",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_bn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_br",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_bs",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ca",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ckb",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_cs",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_cy",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_da",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_dsb",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_el",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_en_au",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_en_gb",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_eo",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_es_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_es_co",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_es_mx",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_es_ni",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_es_ve",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_et",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_eu",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_fa",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_fi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_fy",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ga",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_gd",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_gl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_he",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_hi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_hr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_hsb",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_hu",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_hy",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ia",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ig",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ind",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_io",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_is",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_it",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ja",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ka",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_kab",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_kk",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_km",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_kn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ko",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ky",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_lb",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_lt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_lv",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_mk",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ml",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_mn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_mr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ms",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_my",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_nb",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ne",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_nl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_nn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_os",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_pa",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_pl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_pt_br",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ro",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_sk",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_sl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_sq",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_sr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_sr_latn",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_sv",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_sw",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ta",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_te",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_tg",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_th",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_tk",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_tr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_tt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_udm",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_uk",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_ur",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_vi",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_zh_hans",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="controlledvocabulary",
            name="name_zh_hant",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
