# Generated by Django 4.2.11 on 2024-03-30 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contributors", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationalContributor",
            fields=[],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("contributors.contributor",),
        ),
        migrations.CreateModel(
            name="PersonalContributor",
            fields=[],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("contributors.contributor",),
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="slug",
        ),
    ]
