# Generated by Django 4.2.11 on 2024-03-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('contributors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='organizations.organization'),
        ),
    ]
