# Generated by Django 4.2.11 on 2024-03-25 11:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributors", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ContactPerson", "Contact Person"),
                        ("DataCollector", "Data Collector"),
                        ("DataCurator", "Data Curator"),
                        ("DataManager", "Data Manager"),
                        ("Editor", "Editor"),
                        ("Producer", "Producer"),
                        ("RelatedPerson", "Related Person"),
                        ("Researcher", "Researcher"),
                        ("ProjectLeader", "Project Leader"),
                        ("ProjectManager", "Project Manager"),
                        ("ProjectMember", "Project Member"),
                        ("Supervisor", "Supervisor"),
                        ("WorkPackageLeader", "Work Package Leader"),
                        ("HostingInstitution", "Hosting Institution"),
                        ("ResearchGroup", "Research Group"),
                        ("Sponsor", "Sponsor"),
                        ("RightsHolder", "Rights Holder"),
                        ("Other", "Other"),
                        ("Creator", "Creator"),
                    ],
                    max_length=18,
                ),
                help_text="Assigned roles for this contributor.",
                size=19,
                verbose_name="roles",
            ),
        ),
    ]
