# Generated by Django 5.0.7 on 2024-08-19 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("measurements", "0001_initial"),
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="sample",
            field=models.ForeignKey(
                help_text="The sample on which the measurement was made.",
                on_delete=django.db.models.deletion.PROTECT,
                to="samples.sample",
                verbose_name="sample",
            ),
        ),
        migrations.AddField(
            model_name="description",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="measurements.measurement",
            ),
        ),
        migrations.AddField(
            model_name="date",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="measurements.measurement",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="measurements.measurement",
                verbose_name="measurement",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="description",
            unique_together={("object", "type")},
        ),
        migrations.AlterUniqueTogether(
            name="date",
            unique_together={("object", "type")},
        ),
        migrations.AlterUniqueTogether(
            name="contribution",
            unique_together={("object", "contributor")},
        ),
    ]
