# Generated by Django 3.2.16 on 2022-11-09 10:35

from django.db import migrations, models
import django.db.models.deletion
import djangocms_icon.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', djangocms_icon.fields.Icon(blank=True, default='', max_length=255, verbose_name='Icon')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='geoluminate_cms.icon')),
            ],
            options={
                'db_table': 'core_cms_icon',
            },
        ),
    ]
