# Generated by Django 4.2.1 on 2023-05-10 16:44

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("literature", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("literature.literature",),
        ),
    ]
