# Generated by Django 3.2.17 on 2023-02-01 15:19

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("literature", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("literature.literature",),
        ),
    ]
