# Generated by Django 3.2.15 on 2022-09-27 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crossref', '0002_auto_20220928_0117'),
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crossref.work')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('keywords', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='key words')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('verified_by', models.ManyToManyField(blank=True, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('crossref.work',),
        ),
    ]
