# Generated by Django 3.2.14 on 2022-07-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='crossref_last_queried',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last Crossref query'),
        ),
    ]
