# Generated by Django 3.2.14 on 2022-07-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_crossref_last_queried'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi_queried',
            field=models.BooleanField(default=False, verbose_name='DOI has been queried'),
        ),
    ]
