# Generated by Django 3.2.14 on 2022-07-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_doi_queried'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['family'], 'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-published', 'label'], 'verbose_name': 'publication', 'verbose_name_plural': 'publications'},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='author',
            new_name='authors',
        ),
    ]
