# Generated by Django 3.2.14 on 2022-07-18 10:05

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20220715_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='publications', sort_value_field_name='position', to='publications.Author', verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='label',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='language',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='page',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='publication type'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='volume'),
        ),
    ]
