# Generated by Django 3.2.14 on 2022-08-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20220718_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='authors',
            new_name='author',
        ),
    ]
