# Generated by Django 3.2.14 on 2022-08-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_rename_authors_publication_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='ORCID',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='authenticated_orcid',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='author',
            name='prefix',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='suffix',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='family',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
    ]
