# Generated by Django 3.2.14 on 2022-08-04 09:24

# import ckeditor.fields
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20220802_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('published'), descending=True, nulls_last=True), 'label'], 'verbose_name': 'publication', 'verbose_name_plural': 'publications'},
        ),
        migrations.AlterField(
            model_name='author',
            name='authenticated_orcid',
            field=models.BooleanField(default=None, null=True),
        ),
        # migrations.AlterField(
        #     model_name='publication',
        #     name='abstract',
        #     field=ckeditor.fields.RichTextField(blank=True),
        # ),
    ]
