# Generated by Django 3.2.15 on 2022-08-04 09:47

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20220804_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
