# Generated by Django 3.2.16 on 2022-11-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoluminate_gis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographiclocation',
            options={'ordering': ['name'], 'verbose_name': 'geographic location', 'verbose_name_plural': 'geographic locations'},
        ),
        migrations.AlterField(
            model_name='site',
            name='geographic',
            field=models.ForeignKey(blank=True, help_text='Represents a single country, sea or ocean.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site', to='geoluminate_gis.geographiclocation', verbose_name='geographic location'),
        ),
    ]
