# Generated by Django 3.2.16 on 2022-11-23 15:37

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('geoluminate_gis', '0002_auto_20221114_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='23456789ABCDEFGHJKLMNPQRSTUVWXYZ', blank=True, length=10, max_length=15, prefix='GHFS-', primary_key=True, serialize=False),
        ),
    ]
