# Generated by Django 5.0.7 on 2024-08-13 13:34

import django.db.models.deletion
import django_bleach.models
import geoluminate.contrib.core.models
import geoluminate.contrib.projects.choices
import geoluminate.contrib.projects.models
import geoluminate.db.fields
import imagekit.models.fields
import meta.models
import research_vocabs.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contributors", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Assigned roles for this contributor.",
                        null=True,
                        verbose_name="roles",
                    ),
                ),
                (
                    "store",
                    models.JSONField(
                        default=dict,
                        help_text="A JSON representation of the contributor profile at the time of publication",
                        verbose_name="contributor",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=geoluminate.contrib.core.models.contributor_permissions_default,
                        help_text="A JSON representation of the contributor's permissions at the time of publication",
                        verbose_name="permissions",
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        help_text="The person or organisation that contributed to the project or dataset.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)ss",
                        related_query_name="%(app_label)s_%(class)s",
                        to="contributors.contributor",
                        verbose_name="contributor",
                    ),
                ),
            ],
            options={
                "verbose_name": "contributor",
                "verbose_name_plural": "contributors",
                "abstract": False,
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="Item options.",
                        null=True,
                        verbose_name="options",
                    ),
                ),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to=geoluminate.contrib.projects.models.project_image_path,
                        verbose_name="image",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "funding",
                    models.JSONField(
                        blank=True,
                        help_text="Related funding information.",
                        null=True,
                        verbose_name="funding",
                    ),
                ),
                (
                    "visibility",
                    models.IntegerField(
                        choices=[(0, "Private"), (1, "Public")],
                        default=0,
                        help_text="Visibility within the application.",
                        verbose_name="visibility",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Concept"),
                            (1, "Planning"),
                            (2, "In progress"),
                            (3, "Complete"),
                            (4, "Unknown"),
                        ],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "contributors",
                    models.ManyToManyField(
                        help_text="The contributors to this project.",
                        through="projects.Contribution",
                        to="contributors.contributor",
                        verbose_name="contributors",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_projects",
                        to="organizations.organization",
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "default_related_name": "projects",
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.AddField(
            model_name="contribution",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="projects.project",
                verbose_name="project",
            ),
        ),
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                ("text", django_bleach.models.BleachField()),
                (
                    "type",
                    research_vocabs.fields.ConceptField(
                        max_length=8,
                        verbose_name="type",
                        vocabulary=geoluminate.contrib.projects.choices.ProjectDescriptions,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "description",
                "verbose_name_plural": "descriptions",
                "abstract": False,
                "default_related_name": "descriptions",
                "unique_together": {("object", "type")},
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                ("date", geoluminate.db.fields.PartialDateField(verbose_name="date")),
                (
                    "type",
                    research_vocabs.fields.ConceptField(
                        max_length=9,
                        verbose_name="type",
                        vocabulary=geoluminate.contrib.projects.choices.ProjectDates,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "date",
                "verbose_name_plural": "dates",
                "abstract": False,
                "default_related_name": "dates",
                "unique_together": {("object", "type")},
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name="contribution",
            unique_together={("object", "contributor")},
        ),
    ]
