# Generated by Django 3.2.12 on 2022-02-19 05:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=13)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'continent',
                'verbose_name_plural': 'continents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('iso3', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('region', models.IntegerField(choices=[(2, 'Africa'), (19, 'Americas'), (142, 'Asia'), (150, 'Europe'), (9, 'Oceania')])),
                ('subregion', models.IntegerField(choices=[(14, 'Eastern Africa'), (17, 'Middle Africa'), (15, 'Northern Africa'), (18, 'Southern Africa'), (11, 'Western Africa'), (29, 'Caribbean'), (13, 'Central America'), (5, 'South America'), (21, 'Northern America'), (143, 'Central Asia'), (30, 'Eastern Asia'), (34, 'Southern Asia'), (35, 'South-Eastern Asia'), (145, 'Western Asia'), (151, 'Eastern Europe'), (154, 'Northern Europe'), (39, 'Southern Europe'), (155, 'Western Europe'), (53, 'Australia and New Zealand'), (54, 'Melanesia'), (57, 'Micronesia'), (61, 'Polynesia')])),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'db_table': 'country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ocean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('name', models.CharField(max_length=254)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4236)),
            ],
            options={
                'verbose_name': 'Ocean/Sea',
                'verbose_name_plural': 'Oceans/Seas',
                'db_table': 'global_oceans',
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('plate_id', models.IntegerField()),
                ('plate', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('poly_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=64)),
                ('crust_type', models.CharField(choices=[('C', 'Continental'), ('O', 'Oceanic')], max_length=1)),
                ('domain', models.CharField(blank=True, max_length=64, null=True)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4236)),
            ],
            options={
                'verbose_name': 'tectonic plate',
                'verbose_name_plural': 'tectonic plates',
                'db_table': 'tectonic_plates',
            },
        ),
        migrations.CreateModel(
            name='Political',
            fields=[
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('iso', models.CharField(blank=True, max_length=5, null=True)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Political Region',
                'verbose_name_plural': 'Political Regions',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('group', models.CharField(blank=True, max_length=254, null=True)),
                ('last_orogen', models.CharField(blank=True, max_length=254, null=True)),
                ('crust', models.CharField(blank=True, max_length=254, null=True)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Geological Province',
                'verbose_name_plural': 'Geological Provinces',
                'db_table': 'geological_province',
            },
        ),
    ]
