# Generated by Django 3.2.12 on 2022-04-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plate',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
