# Generated by Django 5.0.4 on 2024-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Logo"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Icon"
                    ),
                ),
                ("database", models.JSONField(default=dict, verbose_name="database")),
                ("authority", models.JSONField(default=dict, verbose_name="authority")),
                ("theme", models.JSONField(default=dict, verbose_name="theme")),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
