# Generated by Django 4.2.11 on 2024-03-30 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="name",
        ),
    ]
