# Generated by Django 3.2.15 on 2022-09-07 13:02

from django.db import migrations, models
import datacite.models


class Migration(migrations.Migration):

    dependencies = [
        ('datacite', '0002_auto_20220906_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='resourceTypeGeneral',
            field=models.CharField(help_text='By setting this option, you can limit submissions through this application to a single resource type.', max_length=256),
        ),
        migrations.AlterField(
            model_name='submission',
            name='publicationYear',
            field=models.PositiveSmallIntegerField(default=datacite.models.current_year, help_text='The year when the data was or will be made publicly available. In the case of resources such as software or dynamic data where there may be multiple releases in one year, include the Date/dateType/ dateInformation property and sub-properties to provide more information  about the publication or release date details.', verbose_name='Publication Year'),
        ),
    ]
