# Generated by Django 5.0.7 on 2024-08-08 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesample',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The sample from which this sample was derived.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsamples', to='samples.basesample', verbose_name='parent sample'),
        ),
    ]
