# Generated by Django 3.2.15 on 2022-09-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapbox_api', models.CharField(blank=True, help_text='Public Mapbox API key to use with kepler.gl. The application will not work until this has been supplied.', max_length=255, null=True, verbose_name='Mapbox API Key')),
                ('default_config', models.JSONField(verbose_name='Default Kepler.gl configuration')),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
    ]
