# Generated by Django 3.2.15 on 2022-09-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepler', '0002_rename_settings_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='default_config',
            field=models.JSONField(default={}, verbose_name='Default Kepler.gl configuration'),
        ),
    ]
