# Generated by Django 3.2.15 on 2022-09-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepler', '0003_alter_configuration_default_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='mapbox_api',
        ),
        migrations.AddField(
            model_name='configuration',
            name='mapbox_token',
            field=models.CharField(blank=True, help_text='Public Mapbox API token to use with kepler.gl. The application will not work until this has been supplied.', max_length=255, null=True, verbose_name='Mapbox API token'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='default_config',
            field=models.JSONField(default={}, help_text='This object contains the full kepler.gl instance configuration {mapState, mapStyle, visState}', verbose_name='Default map configuration'),
        ),
    ]
