# Generated by Django 3.2.15 on 2022-09-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepler', '0005_alter_configuration_default_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='default_lang',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Finish'), ('pt', 'Portuguese'), ('ca', 'Catalan'), ('es', 'Spanish'), ('ja', 'Japanese'), ('cn', 'Chinese'), ('ru', 'Russian')], default='en', help_text="The fallback language to use if the user's current locale is not supported by Kepler.", max_length=2, verbose_name='Default Kepler language'),
        ),
    ]
