# Generated by Django 3.2.15 on 2022-09-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kepler', '0008_auto_20220928_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='fallback_lang',
            new_name='lang',
        ),
    ]
