# Generated by Django 3.2.15 on 2022-09-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepler', '0010_auto_20220928_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='version',
            field=models.CharField(choices=[('v1', 'v1')], default='v1', help_text='Kepler version. Currently only v1 is supported.', max_length=2, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='mapState',
            field=models.JSONField(default=dict, help_text='Configuration object for the map state', verbose_name='map state'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='mapStyle',
            field=models.JSONField(default=dict, help_text='Configuration object for the map style', verbose_name='map style'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='visState',
            field=models.JSONField(default=dict, help_text='Configuration object for the visual state', verbose_name='visual state'),
        ),
    ]
