# Generated by Django 3.2.15 on 2022-09-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepler', '0011_auto_20220928_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('base', 'Base')], default='dark', help_text='The preferred theme to use. Note that preference is given to the browsers prefers-color-scheme setting.', max_length=5, verbose_name='Preferred theme'),
        ),
    ]
