log:
  level: INFO

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true

  https:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: http

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/traefik.yml
    watch: true

api:
  dashboard: true
