# Publishes a new release to GitHub when a new tag is pushed
name: Publish GH Release
on:
  push:
    tags:
      - "v*"
jobs:
  create-gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Release
        uses: softprops/action-gh-release@v1
