# Generated by Django 4.2.1 on 2023-06-29 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="affiliation",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="family",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="given",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="orcid",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="academic_title",
            field=models.CharField(
                blank=True,
                choices=[("Dr.", "Dr."), ("Prof.", "Prof.")],
                max_length=5,
                null=True,
                verbose_name="academic title",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="user.profile",
            ),
        ),
        migrations.CreateModel(
            name="Identifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(max_length=255, verbose_name="identifier"),
                ),
                ("scheme", models.CharField(max_length=255, verbose_name="scheme")),
                ("url", models.URLField(blank=True, null=True, verbose_name="url")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="user.profile",
                    ),
                ),
            ],
        ),
    ]
